export type WindowsRuntimeErrorCode =
  | "RUNTIME_LOCALAPPDATA_MISSING"
  | "RUNTIME_PATH_INVALID"
  | "RUNTIME_PATH_UNC_DISALLOWED"
  | "RUNTIME_PATH_ROOT_DISALLOWED"
  | "RUNTIME_PATH_OVERLAP_DISALLOWED"
  | "RUNTIME_VOLUME_NOT_FIXED"
  | "RUNTIME_REPARSE_POINT_DISALLOWED"
  | "RUNTIME_CLEANUP_TARGET_INVALID"
  | "RUNTIME_CLEANUP_MARKER_INVALID"
  | "RUNTIME_CLEANUP_MARKER_MISMATCH"
  | "RUNTIME_CLEANUP_LOCK_REQUIRED"
  | "RUNTIME_CLEANUP_TARGET_ACTIVE"
  | "RUNTIME_PLATFORM_UNSUPPORTED"
  | "RUNTIME_ROOT_NOT_FOUND"
  | "RUNTIME_ROOT_MARKER_INVALID"
  | "RUNTIME_RUN_MANIFEST_INVALID"
  | "RUNTIME_RUN_ALREADY_EXISTS"
  | "RUNTIME_RUN_NOT_FOUND"
  | "RUNTIME_STORAGE_KEY_INVALID"
  | "RUNTIME_STATE_TOO_LARGE"
  | "RUNTIME_IO_FAILED"
  | "RUNTIME_CLEANUP_LOCK_BUSY"
  | "RUNTIME_CLEANUP_REPARSE_DESCENDANT";

export class WindowsRuntimePolicyError extends Error {
  readonly code: WindowsRuntimeErrorCode;

  constructor(code: WindowsRuntimeErrorCode, options?: ErrorOptions) {
    super(code, options);
    this.name = "WindowsRuntimePolicyError";
    this.code = code;
  }
}
