import { z } from "zod";

export const UploadErrorCodeSchema = z.enum([
  "UPLOAD_REQUEST_INVALID",
  "UPLOAD_MULTIPLE_FILES_NOT_ALLOWED",
  "UPLOAD_FILENAME_INVALID",
  "UPLOAD_UNSUPPORTED_MEDIA",
  "UPLOAD_MIME_MISMATCH",
  "UPLOAD_FILE_EMPTY",
  "UPLOAD_FILE_TOO_LARGE",
  "UPLOAD_CASE_IMAGE_BYTES_EXCEEDED",
  "UPLOAD_SHA256_MISMATCH",
  "UPLOAD_STREAM_INVALID",
  "UPLOAD_IMAGE_METADATA_INVALID",
  "UPLOAD_IMAGE_PIXELS_EXCEEDED",
  "UPLOAD_PDF_METADATA_INVALID",
  "UPLOAD_PDF_PAGES_EXCEEDED",
  "UPLOAD_PDF_TEXT_TOO_LARGE",
  "UPLOAD_PDF_ACTIVE_CONTENT",
  "UPLOAD_PDF_TEXT_UNAVAILABLE",
  "UPLOAD_INLINE_ATTACHMENT_DISALLOWED",
]);

export type UploadErrorCode = z.infer<typeof UploadErrorCodeSchema>;

export type UploadFailure = { ok: false; code: UploadErrorCode };
