export type SharpImageSanitizerErrorCode =
  | "IMAGE_SANITIZER_INPUT_INVALID"
  | "IMAGE_SANITIZER_UNSUPPORTED_MEDIA"
  | "IMAGE_SANITIZER_MIME_MISMATCH"
  | "IMAGE_SANITIZER_FILE_TOO_LARGE"
  | "IMAGE_SANITIZER_PIXEL_LIMIT_EXCEEDED"
  | "IMAGE_SANITIZER_MULTIPAGE_DISALLOWED"
  | "IMAGE_SANITIZER_DECODE_FAILED"
  | "IMAGE_SANITIZER_TIMEOUT"
  | "IMAGE_SANITIZER_DERIVATIVE_INVALID";

export type SharpImageSanitizerFailure = {
  ok: false;
  code: SharpImageSanitizerErrorCode;
};
