export type EvidenceBudgetErrorCode =
  | "EVIDENCE_BUDGET_EXCEEDED"
  | "EVIDENCE_BUDGET_ENGINEERING_ALERT"
  | "EVIDENCE_BUDGET_CONCURRENCY_EXCEEDED"
  | "EVIDENCE_BUDGET_USAGE_UNKNOWN"
  | "EVIDENCE_BUDGET_MODEL_NOT_ALLOWED"
  | "EVIDENCE_BUDGET_INVALID_USAGE"
  | "EVIDENCE_BUDGET_RESERVATION_CONFLICT"
  | "EVIDENCE_BUDGET_RESERVATION_NOT_FOUND"
  | "EVIDENCE_BUDGET_RESERVATION_ALREADY_RECONCILED";

export type EvidenceBudgetDimension =
  "provider_attempts" | "input_tokens" | "output_and_reasoning_tokens";
